#############################################################################
# Generated by PAGE version 4.3.1
# in conjunction with Tcl version 8.6
#    Nov 16, 2014 07:33:21 PM


set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #111111
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top36
    namespace eval ::widgets::$base {
        set set,origin 1
        set set,size 1
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# USER DEFINED PROCEDURES
#

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow. {base} {
    if {$base == ""} {
        set base .
    }
    ###################
    # CREATING WIDGETS
    ###################
    wm focusmodel $top passive
    wm geometry $top 1x1+0+0; update
    wm maxsize $top 1905 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm withdraw $top
    wm title $top "page.tcl"
    bindtags $top "$top Page.tcl all"
    ###################
    # SETTING GEOMETRY
    ###################

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top36 {base} {
    if {$base == ""} {
        set base .top36
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl:toplevel $top -class Toplevel \
        -background {#d9d9d9} 
    wm focusmodel $top passive
    wm geometry $top 600x450+650+150; update
    wm maxsize $top 1905 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel 1"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    bindtags $top "$top Toplevel all _TopLevel"
    listbox $top.lis37 \
        -background white -font TkFixedFont -foreground {#000000} 
    .top36.lis37 configure -font TkFixedFont
    vTcl:DefineAlias "$top.lis37" "Listbox1" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex38 \
        -background white -font TkTextFont -foreground black -height 66 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 376 
    .top36.tex38 configure -font TkTextFont
    .top36.tex38 insert end text
    vTcl:DefineAlias "$top.tex38" "Text1" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex39 \
        -background white -font TkTextFont -foreground black -height 66 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 376 
    .top36.tex39 configure -font TkTextFont
    .top36.tex39 insert end text
    vTcl:DefineAlias "$top.tex39" "Text2" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex40 \
        -background white -font TkTextFont -foreground black -height 66 \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -width 376 
    .top36.tex40 configure -font TkTextFont
    .top36.tex40 insert end text
    vTcl:DefineAlias "$top.tex40" "Text3" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab41 \
        -background {#d9d9d9} -foreground {#000000} -text {Lista de MOTIF} 
    vTcl:DefineAlias "$top.lab41" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab42 \
        -background {#d9d9d9} -foreground {#000000} -text {Secuencia 1} 
    vTcl:DefineAlias "$top.lab42" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab43 \
        -background {#d9d9d9} -foreground {#000000} -text {Secuencia 2} 
    vTcl:DefineAlias "$top.lab43" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab44 \
        -background {#d9d9d9} -foreground {#000000} -text {Secuencia 3} 
    vTcl:DefineAlias "$top.lab44" "Label4" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab46 \
        -background {#d9d9d9} -foreground {#000000} -text {% distancia} 
    vTcl:DefineAlias "$top.lab46" "Label5" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent47 \
        -background white -font TkFixedFont -foreground {#000000} \
        -insertbackground black 
    vTcl:DefineAlias "$top.ent47" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {radio de conservacion} 
    vTcl:DefineAlias "$top.cpd48" "Label6" vTcl:WidgetProc "Toplevel1" 1
    entry $top.cpd50 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.cpd50" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    entry $top.cpd51 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.cpd51" "Entry3" vTcl:WidgetProc "Toplevel1" 1
    label $top.cpd52 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -foreground {#000000} -highlightcolor black \
        -text {% conservacion} 
    vTcl:DefineAlias "$top.cpd52" "Label7" vTcl:WidgetProc "Toplevel1" 1
    button $top.but53 \
        -activebackground {#d9d9d9} -background {#d9d9d9} \
        -foreground {#000000} -highlightcolor black -text Procesar 
    vTcl:DefineAlias "$top.but53" "Procesar" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lis37 \
        -in $top -x 20 -y 50 -width 154 -height 254 -anchor nw \
        -bordermode ignore 
    place $top.tex38 \
        -in $top -x 200 -y 50 -width 376 -height 66 -anchor nw \
        -bordermode ignore 
    place $top.tex39 \
        -in $top -x 200 -y 140 -width 376 -height 66 -anchor nw \
        -bordermode ignore 
    place $top.tex40 \
        -in $top -x 200 -y 230 -width 376 -height 66 -anchor nw \
        -bordermode ignore 
    place $top.lab41 \
        -in $top -x 50 -y 20 -anchor nw -bordermode ignore 
    place $top.lab42 \
        -in $top -x 210 -y 30 -anchor nw -bordermode ignore 
    place $top.lab43 \
        -in $top -x 210 -y 120 -anchor nw -bordermode ignore 
    place $top.lab44 \
        -in $top -x 210 -y 210 -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 40 -y 320 -anchor nw -bordermode ignore 
    place $top.ent47 \
        -in $top -x 150 -y 320 -anchor nw -bordermode ignore 
    place $top.cpd48 \
        -in $top -x 10 -y 350 -anchor nw -bordermode inside 
    place $top.cpd50 \
        -in $top -x 150 -y 380 -anchor nw -bordermode inside 
    place $top.cpd51 \
        -in $top -x 150 -y 350 -anchor nw -bordermode inside 
    place $top.cpd52 \
        -in $top -x 30 -y 380 -anchor nw -bordermode inside 
    place $top.but53 \
        -in $top -x 340 -y 320 -width 237 -height 87 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

Window show .
Window show .top36

