#! /usr/bin/env python
#
# Support module generated by PAGE version 4.3.1
# In conjunction with Tcl version 8.6
#    Nov 16, 2014 07:33:31 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import csv

def fillList():
    with open('in.csv', 'rb') as f:
        reader = csv.reader(f)
        motif_list = map(tuple, reader)

    for item in motif_list:
        w.MultiListBox1.insert(END, item)

def Procesar():
    a = w.MultiListBox1.curselection()
    print w.MultiListBox1.get(a[0])


def init(top, gui, arg=None):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    fillList()

def destroy_window ():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


