#! /usr/bin/env python
#
# Support module generated by PAGE version 4.3.1
# In conjunction with Tcl version 8.6
#    Nov 16, 2014 07:33:31 PM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def fillList():
    for item in ["one", "two", "three", "four", "two", "three", "four", "two", "three", "four", "two", "three", "four", "two", "three", "four", "two", "three", "four", "two", "three", "four"]:
        w.Listbox1.insert(END, item)


def init(top, gui, arg=None):
    global w, top_level, root
    w = gui
    top_level = top
    root = top
    fillList()

def destroy_window ():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


